steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - -f
      - codex/Dockerfile
      - -t
      - us-central1-docker.pkg.dev/srikara-projects/demo-video/codex:latest
      - .
images:
  - us-central1-docker.pkg.dev/srikara-projects/demo-video/codex:latest
timeout: 3600s
options:
  machineType: E2_HIGHCPU_8
  diskSizeGb: 100
